# Generated by Django 4.1.7 on 2023-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pdf_export',
            field=models.FileField(blank=True, null=True, upload_to='prescription/'),
        ),
    ]
