# Generated by Django 4.1.3 on 2022-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
